# Minimal example with just custom logging
# Save this as: examples/train_simple_callbacks.yaml

model_name_or_path: "meta-llama/Llama-2-7b-hf"
stage: "sft" 
do_train: true

# Simple callback configuration
custom_callbacks:
  - "log"  # Just the name for default settings
  - "training_stage"  # Built-in stage callback
  
  # Custom company callback with minimal config
  - name: "callbacks.company2.myExtraLog"
    args:
      log_level: "info"
